name: Lint all markdown files

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Checkout the repository
      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: |
            README.md
            CHANGELOG.md
            docs/*.md
